### ISSUE TITLE
It gives me the link to never gonna give you up

### ISSUE THREAD

**Issue by H4rldev** [justkamiii/token#2]

**Comment by milena-kos** [comment]
this tbh

**Comment by justkamiii** [comment]
I haven't used powercord in a long while, but this seems really odd. Do you have any kind of plugin that does something with the token?

**Comment by milena-kos** [comment]
you can use JS snippet by cynthia from #js-snippets and just paste snippet into console (Ctrl Shift I) to get your token

**Comment by H4rldev** [comment]
It still does it after uninstalling, cleaning cache and restarting the client
